steps:
  - name: 'node:20'
    args: ['npm', 'ci']

  - name: 'node:20'
    args: ['npm', 'run', 'build']

  - name: 'gcr.io/firebase/firebase'
    args:
      - 'deploy'
      - '--only=hosting'
      - '--project=$PROJECT_ID'
      - '--non-interactive'
options:
  logging: CLOUD_LOGGING_ONLY